### ISSUE TITLE
Remove dead footer links

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#25]
On each page there is a footer which links to a few content:
* Creative Commons
* Accessibility
* Term
* Privacy

All these links are dead links for the moment.

My feeling about this would be to remove everything but the Creative Commons link

**Comment by benoit74** [comment]
These links will work once #15 is implemented. Might be better to remove them in the meanwhile, or quickly move on this issue, probably not a complex one btw.

**Comment by benoit74** [comment]
Not sure that content is appropriate for offline archive. @kelson42 : could you have a look at the online version and tell me if you think it is appropriate? Since we are doing an archive, I would expect to keep the content "as-is", but at the same time the information present is often related to the online version.
For instance on the Licensing page (https://fr.ifixit.com/Info/Licensing) they speak a lot about the content that we will produce ... but since this is an archive, nothing will be produced indeed ...

**Comment by kelson42** [comment]
@benoit74 agree, I would just keep the link and put a static content with the CC-BY-BC license.

**Comment by benoit74** [comment]
I finally realized that using iFixit content has the big advantage that it is already translated in all supported languages.
This morning I'm finally more inclined to keep the content as-is.

**Comment by kelson42** [comment]
@benoit74 I better understand now... had a bit of difficulties to understand your PR...

**Comment by benoit74** [comment]
Closing since current situation seems ok, we might reopen if needed anyway.
