### ISSUE TITLE
Remove all links to external content

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#45]
Videos are not scraped (but HTML is still there): they are not removed properly. 

Zimcheck complains about it:

```
 https://www.youtube-nocookie.com/embed/ppSnb4A2WWw?wmode=opaque is an external dependence in article guides/guide_146789.html
  https://www.youtube-nocookie.com/embed/9boRCqvmo6w?wmode=opaque is an external dependence in article guides/guide_146817.html
  https://www.youtube-nocookie.com/embed/LDGR0T5S90w?wmode=opaque is an external dependence in article guides/guide_147067.html
  https://www.youtube-nocookie.com/embed/JTMVuyWZz68?wmode=opaque is an external dependence in article guides/guide_147106.html
  https://www.youtube-nocookie.com/embed/4Qgcym8_Pm4?wmode=opaque is an external dependence in article guides/guide_147124.html
  https://www.youtube-nocookie.com/embed/YGVjv7YoquM?wmode=opaque is an external dependence in article guides/guide_147186.html
  https://www.youtube-nocookie.com/embed/BgN_dT4cud4?wmode=opaque is an external dependence in article guides/guide_147549.html
  https://www.youtube-nocookie.com/embed/BNh9Jqrj8JE?wmode=opaque is an external dependence in article guides/guide_147886.html
  https://www.youtube-nocookie.com/embed/jQ-c_GR7_kA?wmode=opaque is an external dependence in article guides/guide_148042.html
  https://www.youtube-nocookie.com/embed/LxKr0gJVpJ8?wmode=opaque is an external dependence in article guides/guide_148138.html
```

We should probably have an option pour download videos as well, but for the moment, the HTML refereing to them should be properly removed.

**Comment by benoit74** [comment]
We will have a nice page which will display the fact that the content is external + propose to go to this page. This page will be static + some JS code, so that zimcheck won't complain about it + it will be easier to build + it will be quite clear to the user.
Typically the file will be at `home/external_content` and a link to `home/external_content?url=https%3A%2F%2Fwww.urlencoder.io%2F` will state that this content has not been scraped and that the user might go to `https://www.urlencoder.io/` if he wants, but this is external content.

**Comment by kelson42** [comment]
@benoit74 Why not just removing the videos from the DOM?

**Comment by benoit74** [comment]
@kelson42 For multiple reasons :
- because as a user I would expect to not be displayed with a link which goes to any external content without being warned before-hand (your point), but at the same time I believe that the user would like to be able to go see it easily ; if videos are removed, the user won't have any way to find that there was indeed a video and that he might want to go see it when online
- because from a scraper perspective, it is hard to make a difference between a video, a huge image or pdf or whatever file, all are just links to external content which is not scrapped ; on this point, is it normal that zimchecker does not complain on external links to cloudfront which is indeed a big image ? I found one in a guide.
- because in the current situation, the system is displaying content which has been pre-rendered by iFixit, so it is just a bunch of HTML, so probably even harder to know what is behind the link
Does it makes sense or is it an orthogonal view to what you usually do in other scrappers ?

**Comment by kelson42** [comment]
> @kelson42 For multiple reasons :
> 
>     * because as a user I would expect to not be displayed with a link which goes to any external content without being warned before-hand (your point), but at the same time I believe that the user would like to be able to go see it easily ; if videos are removed, the user won't have any way to find that there was indeed a video and that he might want to go see it when online

The approach we have been using so far for all our scrapers is the following: either a resource is here and we display it or it is not here and then we hide it because the content has still a value without it. We don't have so far chosen to take a middle way: make something to invite the user to go online to see the document.

>     * because from a scraper perspective, it is hard to make a difference between a video, a huge image or pdf or whatever file, all are just links to external content which is not scrapped ; on this point, is it normal that zimchecker does not complain on external links to cloudfront which is indeed a big image ? I found one in a guide.

A link to an external page is not a problem. But here we talk about a resource which is necessary to display the HTML page properly. Zimchecker should complain for any external resource (because the page should perfectly be displayed without Internet access). If it does not this is a bug.

It is almost impossible to reach that goal without tweaking a bit the HTML. It's not the goal to do many of such things, but it is "impossible" to avoid that part. CSS selectors are your friends.

>     * because in the current situation, the system is displaying content which has been pre-rendered by iFixit, so it is just a bunch of HTML, so probably even harder to know what is behind the link
>       Does it makes sense or is it an orthogonal view to what you usually do in other scrappers ?

I'm not against your approach of inviting users to go online to see the video. I think this is less good than making a version without and another with videos. But this is maybe worth a try. Maybe @rgaudin, @Popolechien and @mgautierfr have thoughs about that.

**Comment by benoit74** [comment]
OK, I consider I will go "my way", to see if it makes sense, as a "try" like you said.
See #55 for other implementation details.
