### ISSUE TITLE
URL are not meaninfull

### ISSUE THREAD

**Issue by kelson42** [openzim/ifixit#46]
URLs (for example `guides/guide_147124.html` suffer of a few weaknesses:
* There is a redundancy (twice `guide` is not necessary)
* They end-up with `.html` with is not necessary (an IMO a bit ugly)
* They are not meaninful (a slug of the title would be better)

We should IMO better have something like: `guide/galaxy-a71-fpc-repair`.

Here an example with a SE forum:
https://library.kiwix.org/beer_stackexchange_com_2021-12/questions/518/do-cans-change-the-taste-of-beer

**Comment by kelson42** [comment]
@rgaudin I believe python-scraperlib helps here to do that relatively easily. Right?

**Comment by rgaudin** [comment]
The Creator allows setting any URL indeed. I'm in favor of replicating what's on the source website in general. It's the most straightforward for both users and maintenance.

**Comment by kelson42** [comment]
Here is the original article https://fr.ifixit.com/Tutoriel/Galaxy+A71+FPC+Repair/147124

**Comment by benoit74** [comment]
I agree, this is definitely doable indeed, even probably quite easy, the current filename is indeed a remaining artefact of the first PoC where I stored all files locally before ziming them with zimwriterfs and it was a pain to create directory structures on the fly.

**Comment by benoit74** [comment]
@rgaudin @kelson42 
I'm facing an issue on this one.
While working well on most cases, this change also generates a lot of broken links.
This has to do with the handling of "unusual" characters in titles.

For instance, all URLs below are working well on iFixit and all redirect to the same page:
```
https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adh%C3%A9sives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936
https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adhésives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936
https://fr.ifixit.com/Tutoriel/Remplacement des bandes adhésives fixant la batterie d'un iPhone 8, 8 Plus ou XR/103936
https://fr.ifixit.com/Tutoriel/Remplacement des bandes adhésives fixant la batterie d'un iPhone 8 8 Plus ou XR/103936
```

But they are definitely not equivalent from a kiwix-serve point of view. I tried to generate few redirects automatically (typically replacing "spaces" with "plus") but it is not sufficient.

I also have an issue with items with a "/" in their names, which are breaking relative links I have to use since we can't use absolute links in Kiwix.

Do you have any advice on how to fix this situation ?

I'm seriously considering a rollback to a less meaningful URL naming convention:
```
/Guide/103936
/User/103936
/Device/Mac
/Info/FAQ
``` 
Devices and Infos will stay with their nice names since it seems to be way more under control that guide titles and user names.

While not very "nice-looking", this would probably ensure that very few dead-link are generated.

**Comment by rgaudin** [comment]
@benoit74 the first two are different representations of the same URL (url2).

```py
In [1]: url1 = "https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adh%C3%A9sives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936"
   ...: url2 = "https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adhésives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936"
   ...: url3 = "https://fr.ifixit.com/Tutoriel/Remplacement des bandes adhésives fixant la batterie d'un iPhone 8, 8 Plus ou XR/103936"
   ...: url4 = "https://fr.ifixit.com/Tutoriel/Remplacement des bandes adhésives fixant la batterie d'un iPhone 8 8 Plus ou XR/103936"

In [2]: import urllib.parse

In [3]:  urllib.parse.unquote(url1)
Out[3]: "https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adhésives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936"

In [4]:  urllib.parse.unquote(url1) == url2
Out[4]: True
```

The browser would transform the first one into the second one automatically when making a request. You can check that by running a local webserver with logs and testing the first url as well

```sh
caddy file-server -listen 0.0.0.0:8888 -root . --access-log /dev/stdout browse
# in a different terminal
curl "http://localhost:8888/Tutoriel/Remplacement+des+bandes+adh%C3%A9sives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936"
```

What I suggest is that you consistently *normalize* URLs you get from ifixit (unquoted is appropriate) and only store that in the Creator.

This will fix `url1` being different than `url2`.

`url3` and `url4` are different URLs that should redirect to the one you define as source (`url2` in this case). Nothing special on the ZIM side but you'd need a way to recognize those so you create the appropriate redirect instead. This could be based on the returned `Location` if you plan in making such requests or you could go the fastest but tricker regexp route.

```py
urllib.parse.unquote(requests.head(url3).headers.get("Location"))
urllib.parse.unquote(requests.head(url4).headers.get("Location"))
```

**Comment by benoit74** [comment]
Thank you so much for the trick !

I unfortunately quickly found a situation where the `Location` header is unfortunately missing ... (the backend does not return it).

```
>>> url5 = "https://fr.ifixit.com/Info/What"
```

```
def get_norm_url(url):
   parsed_url = urllib.parse.urlparse(url)
   parsed_url_quoted = [parsed_url.scheme, parsed_url.netloc, urllib.parse.quote(parsed_url.path), parsed_url.params, parsed_url.query, parsed_url.fragment]
   return urllib.parse.unquote(urllib.request.urlopen(urllib.parse.urlunparse(parsed_url_quoted)).geturl())
```

With url3:
```
>>> get_norm_url(url3)
"https://fr.ifixit.com/Tutoriel/Remplacement+des+bandes+adhésives+fixant+la+batterie+d'un+iPhone+8+8+Plus+ou+XR/103936"
```

With url5:
```
>>> get_norm_url(url5)
"https://fr.ifixit.com/Info/what"
```
(notice the lower case 'w' which can not be hinted ...)

**Comment by rgaudin** [comment]
I don't understand the problem with `url5` to be honest:

```py
urllib.parse.unquote(requests.head(url5).headers.get("Location"))
# 'https://fr.ifixit.com/Info/what'
```

So `url5` has the Location header and its target doesn't because it's the *source* URL and not a redirect.

I'm not sure I understand exactly what goes on on your normalization function but scraperlib's [`rebuild_uri()`](https://github.com/openzim/python-scraperlib/blob/master/src/zimscraperlib/uri.py) may make your code simpler to edit an URI.

I'm curious about why you'd be using `urlopen` instead of `requests` module. `requests` is quite powerful and we use it everywhere (expect for no-dependencies scripts). If trying to retrieve the redirect from the response in a single pass:

```py
# with urlopen
urllib.request.urlopen("https://wiki.kiwix.org").url
'https://wiki.kiwix.org/wiki/Special:MyLanguage/Main_Page'

# with requests
requests.head("https://wiki.kiwix.org", allow_redirects=True).url
'https://wiki.kiwix.org/wiki/Special:MyLanguage/Main_Page'
```

Advantage of requests here is that you'd still only make HEAD requests which are lightweight and won't pollute the server's logs. It's good to know that some app servers don't handle HEAD requests. In that case, we use `requests.get(url, stream=True)` which makes a minimal connection without consuming/transfering the data (equivalent to `urlopen`)

**Comment by benoit74** [comment]
Hi @rgaudin 
Thank you for all your hints. Indeed it seems that now there is a location header with `url5`. I don't know if I messed up (it looks like the location header is not displayed in curl but still available in python ...) or if something changed on iFixit side.
Anyway, it is right that is works with the following code :
```
location = requests.head(href).headers.get("Location")
if location is None:
    location = requests.get(href, stream=True).url
``` 
I removed the _normalization_ part for now because I faced some issues with invalid URLs in my generated HTML code. I realize that it is unclear for me why / when this _normalization_ was needed in fact. Should I _normalize_ only for the Creator path and use the _quoted_ version for HTML documents ? What is the issue if I use the _quoted_ version for Creator path as well ? (aside from less readable URLs)

**Comment by rgaudin** [comment]
If you use the quoted version in creator, the risk is that the browser decodes it and sends a request to the *raw* version to the ZIM reader and that would not be found as kiwixlib does zero transformation: it simply returns matching Entry

**Comment by benoit74** [comment]
Ah yes, I got it, thank you
